### ISSUE TITLE
解析js文件不生效

### ISSUE THREAD

**Issue by myinlg** [dravenww/vite-plugin-react-js-support#1]
请问有项目案例吗，按文档上来还是不生效
![image](https://user-images.githubusercontent.com/37045183/116787170-45c18b00-aad5-11eb-9fe7-d6ce7721ef64.png)

**Comment by dravenww** [comment]
辛苦提供一下demo，谢谢

**Comment by myinlg** [comment]
感觉这个vite报错有点问题，后来重启就没有报jsx的问题了

**Comment by dravenww** [comment]
> 感觉这个vite报错有点问题，后来重启就没有报jsx的问题了

好的。
