### ISSUE TITLE
原来的react项目中jsx文件都是js后缀,使用此插件后,还是报错

### ISSUE THREAD

**Issue by bingyeby** [dravenww/vite-plugin-react-js-support#2]
![image](https://user-images.githubusercontent.com/17765117/120282026-42940780-c2ec-11eb-8de3-bf6171b9cb5a.png)
![image](https://user-images.githubusercontent.com/17765117/120282470-b7674180-c2ec-11eb-86c7-4a64a88906f2.png)

**Comment by bingyeby** [comment]
我的关注点在这里:
![image](https://user-images.githubusercontent.com/17765117/120282269-8129c200-c2ec-11eb-945c-c37cfc66c2c0.png)
https://esbuild.github.io/content-types/#jsx

**Comment by dravenww** [comment]
你的react版本应该是16吧，没到17吧？
这个插件的作用是在17版本后的js文件内注入react的引入，17之前的版本都是须要手动引入react的

**Comment by bingyeby** [comment]
react版本是16,但这个看着像是jsx解析不了,与注入react引用有关联么

**Comment by dravenww** [comment]
没有关联，确实是jsx解析不了，不过这个插件已经进行了jsx的编译处理了哇

**Comment by hanayashiki** [comment]
真是令人草生，rename js -> jsx 一键搞定
